[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter backend exec prisma generate", "pnpm --filter backend exec prisma migrate deploy", "pnpm --filter backend build"]

[start]
cmd = "cd apps/backend && node dist/src/main.js"
