[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/backend && npx prisma generate --schema=./prisma/schema.prisma && pnpm run build"]

[start]
cmd = "cd apps/backend && npx prisma migrate deploy --schema=./prisma/schema.prisma && node dist/src/main.js"
