[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter backend exec prisma generate", "pnpm --filter backend build"]

[start]
cmd = "cd apps/backend && npx prisma migrate deploy && npx prisma generate && node dist/src/main.js"
